![title](edel.JPG)

# Edelweiss Hackathon-Machine Learning

## Predict Forclosure Probability

### Problem Statement

India is a diversified financial sector undergoing rapid expansion, both in terms of strong growth of existing financial services firms and new entities entering the market. The sector comprises commercial banks, insurance companies, non-banking financial companies, co-operatives, pension funds, mutual funds and other smaller financial entities .
The Edelweiss Group is one of India&#39;s leading diversified financial services company providing a broad range of financial products and services to a substantial and diversified client base that includes corporations, institutions and individuals. Edelweiss&#39;s products and services span multiple asset classes and consumer segments across domestic and global geographies.
Given the availability of various alternatives across the industry customer has a propensity to move to another financial institution for Balance Transfer. Foreclosure and balance transfer has added to the concerns of NBFCs. Foreclosure means repaying the outstanding loan amount in a single payment instead of with EMIs while balance transfer is transferring outstanding Loan availed from one Bank / Financial Institution to another Bank / Financial Institution, usually on the grounds of better service, top-up on the existing loan, proximity of branch, saving on interest repayments, etc. Losing out on customers on grounds on foreclosure and balance transfer leads to revenue loss. Acquiring a new customer can cost up to five times more than retaining an existing customer and an increase in customer retention by 5% increases profits up to 25%.
NBFCs have started taking pro-active measures to ensure this is curbed; and this is where you come in! Objective is primarily to arrive at a propensity to foreclose and balance transfer an existing loan based on lead indicators such as demographics, internal behavior and performance on all credit lines; along with the estimated ‘Time to Foreclose’. May the best algorithm win!

Participants are free to use any openly available data source to further enrich the dataset.


### Data Description
We have provided the following dataset:
* **Customer demographics**
* **Customer transactions (ie. repayments made by the client)**
* **List of foreclosed customers **
* **Email interaction of the customer with the customer representative**

The participants are expected to predict the probability of foreclosure for each of the data points in the test set.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input/foreclosure-prediction-dataset"))

# Any results you write to the current directory are saved as output.

['test_foreclosure.csv', 'RF_Final_Data.xlsx', 'LMS_31JAN2019.xlsx', 'Customers_31JAN2019.xlsx', 'train_foreclosure.csv']

In [2]:
train=pd.read_csv('../input/foreclosure-prediction-dataset/train_foreclosure.csv')
test=pd.read_csv('../input/foreclosure-prediction-dataset/test_foreclosure.csv')
final=pd.read_excel('../input/foreclosure-prediction-dataset/RF_Final_Data.xlsx')
tran1=pd.read_excel('../input/foreclosure-prediction-dataset/LMS_31JAN2019.xlsx')
cust=pd.read_excel('../input/foreclosure-prediction-dataset/Customers_31JAN2019.xlsx')
tran1.head()

   AGREEMENTID  CUSTOMERID ...   NPA_IN_CURRENT_MONTH  MOB
0     11220001  12001000.0 ...                    NaN   39
1     11220002  12001001.0 ...                    NaN   38
2     11220003  12001002.0 ...                    NaN   38
3     11220004  12001003.0 ...                    NaN   38
4     11220005  12001004.0 ...                    NaN   38

[5 rows x 38 columns]

In [3]:

tran=tran1.copy()

### Customer data

In [4]:
cust.head()

   CUSTOMERID       ...        BRANCH_PINCODE
0    12001000       ...              400070.0
1    12001001       ...              400070.0
2    12001002       ...              400070.0
3    12001003       ...              400070.0
4    12001004       ...              400070.0

[5 rows x 15 columns]

### Email Interaction

In [5]:
final.head()

   TicketId     Type        ...         Masked_CustomerID Masked_AgreementID
0    571910  REQUEST        ...                  12020736                  0
1    572747  REQUEST        ...                  12019080                  0
2      4622  General        ...                  12004815                  0
3      4674  REQUEST        ...                  12005158           11230237
4      4681    QUERY        ...                  12001022                  0

[5 rows x 9 columns]

In [6]:
print(len(np.intersect1d(final['Masked_AgreementID'].values,tran.AGREEMENTID)))
print(len(np.intersect1d(final['Masked_CustomerID'].values,tran.CUSTOMERID)))

401
2709

In [7]:
tran.sample(10)

        AGREEMENTID  CUSTOMERID ...   NPA_IN_CURRENT_MONTH  MOB
186692     11228417  12009416.0 ...                    NaN   11
329269     11236054  12017053.0 ...                    NaN    4
80829      11221939  12002938.0 ...                    NaN   30
343726     11235915  12016914.0 ...                    NaN    5
283653     11231127  12012126.0 ...                      0   12
85193      11227027  12008026.0 ...                    NaN    4
108326     11222950  12003949.0 ...                    NaN   27
364452     11239060  12020059.0 ...                    NaN    3
190545     11232440  12013439.0 ...                    NaN    0
209063     11231858  12012857.0 ...                    NaN    4

[10 rows x 38 columns]

In [8]:
def tran_finalagg(val):
    if val in list(set(final['Masked_AgreementID'])):
        return 1
    else:
        return 0
# def tran_finalcust(val):
#     if val in list(set(final['Masked_CustomerID'])):
#         return 1
#     else:
#         return 0
# def tran_cust(val):
#     if val in list(set(cust['CUSTOMERID'])):
#         return 1
#     else:
#         return 0
tran['IS_TRAN_FINAL_AGG']=tran['AGREEMENTID'].apply(tran_finalagg)
# tran['IS_AGG_FINAL_CUST']=tran['AGREEMENTID'].apply(tran_finalcust)
# tran['IS_TRAN_CUST']=tran['AGREEMENTID'].apply(tran_cust)
tran.head()

   AGREEMENTID  CUSTOMERID        ...          MOB  IS_TRAN_FINAL_AGG
0     11220001  12001000.0        ...           39                  0
1     11220002  12001001.0        ...           38                  0
2     11220003  12001002.0        ...           38                  0
3     11220004  12001003.0        ...           38                  0
4     11220005  12001004.0        ...           38                  0

[5 rows x 39 columns]

In [9]:
tran.columns

Index(['AGREEMENTID', 'CUSTOMERID', 'LOAN_AMT', 'NET_DISBURSED_AMT',
       'INTEREST_START_DATE', 'CURRENT_ROI', 'ORIGNAL_ROI', 'CURRENT_TENOR',
       'ORIGNAL_TENOR', 'DUEDAY', 'AUTHORIZATIONDATE', 'CITY',
       'PRE_EMI_DUEAMT', 'PRE_EMI_RECEIVED_AMT', 'PRE_EMI_OS_AMOUNT',
       'EMI_DUEAMT', 'EMI_RECEIVED_AMT', 'EMI_OS_AMOUNT', 'EXCESS_AVAILABLE',
       'EXCESS_ADJUSTED_AMT', 'BALANCE_EXCESS', 'NET_RECEIVABLE',
       'OUTSTANDING_PRINCIPAL', 'PAID_PRINCIPAL', 'PAID_INTEREST',
       'MONTHOPENING', 'LAST_RECEIPT_DATE', 'LAST_RECEIPT_AMOUNT', 'NET_LTV',
       'COMPLETED_TENURE', 'BALANCE_TENURE', 'DPD', 'FOIR', 'PRODUCT',
       'SCHEMEID', 'NPA_IN_LAST_MONTH', 'NPA_IN_CURRENT_MONTH', 'MOB',
       'IS_TRAN_FINAL_AGG'],
      dtype='object')

In [10]:
# pd.get_dummies(tran,columns=['PRODUCT'],drop_first=True).head().value
tran['CITY'].value_counts()

MUMBAI              71980
HYDERABAD           56724
PUNE                44538
AHMEDABAD           43812
SURAT               41441
CHENNAI             35428
BANGALORE           28041
DELHI               20421
THANE               19831
COIMBATORE          17552
MADURAI             16091
RAJKOT              12191
ERODE                8890
TIRUCHIRAPPALLI      8392
NASHIK               8249
TIRUPUR              7662
WARANGAL             7493
VISHAKHAPATNAM       7195
VADODARA             6803
NAGPUR               6802
KARUR                6650
NAMAKKAL             6578
TUTICORIN            6313
NAVI MUMBAI          6218
NELLORE              6030
PONDICHERRY          5909
SALEM                5534
TIRUNELVELI          4556
MYSORE               4429
VELLORE              4342
                    ...
ERNAKULAM               7
BULDHANA                7
VETTAIKARANPUDUR        7
AMBAJI                  7
PALWAL                  7
MAHAD                   6
CHAMARAJANAGAR          6
BHANDARA                6
CHIK BALLAPUR           6
MAHASAMUND              6
DAHANU                  5
OSMANABAD               5
POLLACHI                5
VADGAM                  5
TULJAPUR                5
PACHORA                 5
POONCH                  5
NANDED                  4
UPLETA                  4
HINGANGHAT              4
AMBALA                  3
KUNDGOL                 3
JODHPUR                 3
PARBHANI                3
PALANI                  2
KALLUR                  2
RATLAM                  1
KUTCH                   1
EKAMBARA KUPPAM         1
NANDURBAR               1
Name: CITY, Length: 316, dtype: int64

### Feature Engineering

In [11]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
tran['CITY'].fillna('OTHERS',inplace=True)
tran['CITY']=l1.fit_transform(tran['CITY'])
# tran['CUSTOMERID']=tran['CUSTOMERID'].astype(np.object)
# tran['SCHEMEID']=tran['SCHEMEID'].astype(np.object)
tran=pd.get_dummies(tran,columns=['PRODUCT'],drop_first=True)
tran['last_auth_d']=((tran['LAST_RECEIPT_DATE']-tran['AUTHORIZATIONDATE'])/np.timedelta64(1,'D')).fillna(0)
tran['last_auth_m']=((tran['LAST_RECEIPT_DATE']-tran['AUTHORIZATIONDATE'])/np.timedelta64(1,'M')).fillna(0)
tran['last_auth_y']=((tran['LAST_RECEIPT_DATE']-tran['AUTHORIZATIONDATE'])/np.timedelta64(1,'Y')).fillna(0)

tran['last_int_d']=((tran['LAST_RECEIPT_DATE']-tran['INTEREST_START_DATE'])/np.timedelta64(1,'D')).fillna(0)
tran['last_int_m']=((tran['LAST_RECEIPT_DATE']-tran['INTEREST_START_DATE'])/np.timedelta64(1,'M')).fillna(0)
tran['last_int_y']=((tran['LAST_RECEIPT_DATE']-tran['INTEREST_START_DATE'])/np.timedelta64(1,'Y')).fillna(0)

tran['auth_int_d']=((tran['AUTHORIZATIONDATE']-tran['INTEREST_START_DATE'])/np.timedelta64(1,'D')).fillna(0)
tran['auth_int_m']=((tran['AUTHORIZATIONDATE']-tran['INTEREST_START_DATE'])/np.timedelta64(1,'M')).fillna(0)
tran['auth_int_y']=((tran['AUTHORIZATIONDATE']-tran['INTEREST_START_DATE'])/np.timedelta64(1,'Y')).fillna(0)

# tran['CUSTOMERID']=tran['CUSTOMERID'].astype(np.object)
tran['CUSTOMERID'].fillna(12009999,inplace=True)
# tran['SCHEMEID']=tran['SCHEMEID'].astype(np.object)
tran['SCHEMEID'].fillna(10909999,inplace=True)
tran['LAST_RECEIPT_AMOUNT'].fillna(tran['LAST_RECEIPT_AMOUNT'].mean(),inplace=True)

tran['ROI_DIFF']=tran['CURRENT_ROI']-tran['ORIGNAL_ROI']
tran['TENOR_DIFF']=tran['CURRENT_TENOR']-tran['ORIGNAL_TENOR']
tran['AMT_DIFF']=tran['LOAN_AMT']-tran['NET_DISBURSED_AMT']
# tran.isnull().sum()

In [12]:
tran.isnull().sum()

AGREEMENTID                   0
CUSTOMERID                    0
LOAN_AMT                      0
NET_DISBURSED_AMT             0
INTEREST_START_DATE           0
CURRENT_ROI                   0
ORIGNAL_ROI                   0
CURRENT_TENOR                 5
ORIGNAL_TENOR                 0
DUEDAY                        0
AUTHORIZATIONDATE             0
CITY                          0
PRE_EMI_DUEAMT                0
PRE_EMI_RECEIVED_AMT          0
PRE_EMI_OS_AMOUNT             0
EMI_DUEAMT                    0
EMI_RECEIVED_AMT              0
EMI_OS_AMOUNT                 0
EXCESS_AVAILABLE              0
EXCESS_ADJUSTED_AMT           0
BALANCE_EXCESS                0
NET_RECEIVABLE                0
OUTSTANDING_PRINCIPAL         0
PAID_PRINCIPAL                0
PAID_INTEREST                 0
MONTHOPENING                  0
LAST_RECEIPT_DATE          3787
LAST_RECEIPT_AMOUNT           0
NET_LTV                       0
COMPLETED_TENURE              0
BALANCE_TENURE                5
DPD                          31
FOIR                          0
SCHEMEID                      0
NPA_IN_LAST_MONTH        610891
NPA_IN_CURRENT_MONTH     610814
MOB                           0
IS_TRAN_FINAL_AGG             0
PRODUCT_LAP                   0
PRODUCT_STHL                  0
PRODUCT_STLAP                 0
last_auth_d                   0
last_auth_m                   0
last_auth_y                   0
last_int_d                    0
last_int_m                    0
last_int_y                    0
auth_int_d                    0
auth_int_m                    0
auth_int_y                    0
ROI_DIFF                      0
TENOR_DIFF                    5
AMT_DIFF                      0
dtype: int64

In [13]:
tran.describe(include='all').T

                        count unique     ...               75%          max
AGREEMENTID            624250    NaN     ...       1.12359e+07  1.12534e+07
CUSTOMERID             624250    NaN     ...       1.20169e+07  1.20339e+07
LOAN_AMT               624250    NaN     ...       5.20973e+06  5.70492e+08
NET_DISBURSED_AMT      624250    NaN     ...        5.1669e+06  5.67459e+08
INTEREST_START_DATE    624250   1847     ...               NaN          NaN
CURRENT_ROI            624250    NaN     ...           17.1676      37.4566
ORIGNAL_ROI            624250    NaN     ...           16.5433      34.1479
CURRENT_TENOR          624245    NaN     ...               203          713
ORIGNAL_TENOR          624250    NaN     ...               180          300
DUEDAY                 624250    NaN     ...                 5           15
AUTHORIZATIONDATE      624250   2481     ...               NaN          NaN
CITY                   624250    NaN     ...               231          316
PRE_EMI_DUEAMT         624250    NaN     ...           36074.5  3.17754e+07
PRE_EMI_RECEIVED_AMT   624250    NaN     ...           36074.5  3.17754e+07
PRE_EMI_OS_AMOUNT      624250    NaN     ...                 0  2.08913e+06
EMI_DUEAMT             624250    NaN     ...       1.40364e+06  3.93639e+08
EMI_RECEIVED_AMT       624250    NaN     ...       1.37193e+06  3.88801e+08
EMI_OS_AMOUNT          624250    NaN     ...                 0  5.89953e+07
EXCESS_AVAILABLE       624250    NaN     ...           1329.55  2.84164e+08
EXCESS_ADJUSTED_AMT    624250    NaN     ...           260.609  2.84164e+08
BALANCE_EXCESS         624250    NaN     ...           1.10428    7.735e+07
NET_RECEIVABLE         624250    NaN     ...                 0   5.6725e+07
OUTSTANDING_PRINCIPAL  624250    NaN     ...       4.65499e+06  5.67459e+08
PAID_PRINCIPAL         624250    NaN     ...            212952  4.88522e+09
PAID_INTEREST          624250    NaN     ...            764007  1.84553e+08
MONTHOPENING           624250    NaN     ...       4.85036e+06  5.67459e+08
LAST_RECEIPT_DATE      620463   1664     ...               NaN          NaN
LAST_RECEIPT_AMOUNT    624250    NaN     ...             39953  8.49688e+07
NET_LTV                624250    NaN     ...             64.84       104.86
COMPLETED_TENURE       624250    NaN     ...                23           98
BALANCE_TENURE         624245    NaN     ...               182          693
DPD                    624219    NaN     ...                 0         2268
FOIR                   624250    NaN     ...              0.69       547616
SCHEMEID               624250    NaN     ...       1.09013e+07    1.091e+07
NPA_IN_LAST_MONTH       13359      5     ...               NaN          NaN
NPA_IN_CURRENT_MONTH    13436      3     ...               NaN          NaN
MOB                    624250    NaN     ...                24           98
IS_TRAN_FINAL_AGG      624250    NaN     ...                 0            1
PRODUCT_LAP            624250    NaN     ...                 1            1
PRODUCT_STHL           624250    NaN     ...                 1            1
PRODUCT_STLAP          624250    NaN     ...                 0            1
last_auth_d            624250    NaN     ...               734         2962
last_auth_m            624250    NaN     ...           24.1155      97.3162
last_auth_y            624250    NaN     ...           2.00962      8.10968
last_int_d             624250    NaN     ...               731         2962
last_int_m             624250    NaN     ...           24.0169      97.3162
last_int_y             624250    NaN     ...           2.00141      8.10968
auth_int_d             624250    NaN     ...                 0           17
auth_int_m             624250    NaN     ...                 0     0.558533
auth_int_y             624250    NaN     ...                 0    0.0465444
ROI_DIFF               624250    NaN     ...                 0      24.3468
TENOR_DIFF             624245    NaN     ...                 0          467
AMT_DIFF               624250    NaN     ...                 0  1.77987e+08

[53 rows x 13 columns]

**Building more features**

In [14]:
['mean','sum','min','max','median','quantile','mad','std','count','nunique']
ag_cat=['sum', 'mean','count','nunique','min','max']
ag_num=['mean','sum','min','max','median','quantile','mad','std']
agg_func = {
    'CUSTOMERID': ag_cat,
    'LOAN_AMT': ['mean','sum','min','max','median','quantile','mad','std'],
    'NET_DISBURSED_AMT': ag_num,
#     'INTEREST_START_DATE': ag_num,
    'CURRENT_ROI': ag_num,
    'ORIGNAL_ROI': ag_num,
    'CURRENT_TENOR': ag_num,
    'ORIGNAL_TENOR': ag_num,
    'DUEDAY': ag_cat,
#     'AUTHORIZATIONDATE': ag_num,
    'CITY': ag_cat,
    'PRE_EMI_DUEAMT': ag_num,
    'PRE_EMI_RECEIVED_AMT': ag_num,
    'PRE_EMI_OS_AMOUNT': ag_num,
    'EMI_DUEAMT': ag_num,
    'EMI_RECEIVED_AMT': ag_num,
    'EMI_OS_AMOUNT': ag_num,
    'EXCESS_AVAILABLE': ag_num,
    'EXCESS_ADJUSTED_AMT': ag_num,
    'BALANCE_EXCESS': ag_num,
    'NET_RECEIVABLE': ag_num,
    'OUTSTANDING_PRINCIPAL': ag_num,
    'PAID_PRINCIPAL': ag_num,
    'PAID_INTEREST': ag_num,
    'MONTHOPENING': ag_num,
#     'LAST_RECEIPT_DATE': ag_num,
    'LAST_RECEIPT_AMOUNT':ag_num,
    'NET_LTV': ag_num,
    'COMPLETED_TENURE': ag_num,
    'BALANCE_TENURE': ag_num,
    'DPD': ag_num,
    'last_auth_y': ag_num,
    'last_int_d': ag_num,
    'last_int_m':ag_num,
    'last_int_y': ag_num,
    'auth_int_d': ag_num,
    'auth_int_m':ag_num,
    'auth_int_y': ag_num,
    'FOIR': ag_num,
    'SCHEMEID': ag_cat,
    'ROI_DIFF': ag_num,
    'TENOR_DIFF': ag_num,
    'AMT_DIFF':ag_num,
    'IS_TRAN_FINAL_AGG': ag_num,
    'MOB':ag_cat,
    'PRODUCT_STHL': ag_num,
    'PRODUCT_STLAP': ag_num,
    'PRODUCT_LAP':ag_num,
    'last_auth_d':ag_num,
    'last_auth_m':ag_num,
    'NPA_IN_LAST_MONTH':['count','nunique'],
    'NPA_IN_CURRENT_MONTH':['count','nunique']
    }

print(len(agg_func))
print(len(tran.columns))

49
53

Combining dataset

In [15]:
df=tran.groupby(by=['AGREEMENTID']).agg(agg_func)
df.columns=['LMS' + '_'.join(col).strip() for col in df.columns.values]
df.reset_index(inplace=True)
# df=df.append(tran.groupby(by=['AGREEMENTID']).std().reset_index())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33354 entries, 0 to 33353
Columns: 371 entries, AGREEMENTID to LMSNPA_IN_CURRENT_MONTH_nunique
dtypes: float64(320), int64(37), uint8(14)
memory usage: 91.3 MB

In [18]:
df.head()

   AGREEMENTID               ...                 LMSNPA_IN_CURRENT_MONTH_nunique
0     11220001               ...                                               0
1     11220002               ...                                               0
2     11220003               ...                                               1
3     11220004               ...                                               0
4     11220005               ...                                               0

[5 rows x 371 columns]

In [19]:
# cust1=cust.drop(['PROFESSION','OCCUPATION','POSITION','PRE_JOBYEARS'],axis=1)
# cust1.head()
df.isnull().sum()

AGREEMENTID                           0
LMSCUSTOMERID_sum                     0
LMSCUSTOMERID_mean                    0
LMSCUSTOMERID_count                   0
LMSCUSTOMERID_nunique                 0
LMSCUSTOMERID_min                     0
LMSCUSTOMERID_max                     0
LMSLOAN_AMT_mean                      0
LMSLOAN_AMT_sum                       0
LMSLOAN_AMT_min                       0
LMSLOAN_AMT_max                       0
LMSLOAN_AMT_median                    0
LMSLOAN_AMT_quantile                  0
LMSLOAN_AMT_mad                       0
LMSLOAN_AMT_std                    1086
LMSNET_DISBURSED_AMT_mean             0
LMSNET_DISBURSED_AMT_sum              0
LMSNET_DISBURSED_AMT_min              0
LMSNET_DISBURSED_AMT_max              0
LMSNET_DISBURSED_AMT_median           0
LMSNET_DISBURSED_AMT_quantile         0
LMSNET_DISBURSED_AMT_mad              0
LMSNET_DISBURSED_AMT_std           1086
LMSCURRENT_ROI_mean                   0
LMSCURRENT_ROI_sum                    0
LMSCURRENT_ROI_min                    0
LMSCURRENT_ROI_max                    0
LMSCURRENT_ROI_median                 0
LMSCURRENT_ROI_quantile               0
LMSCURRENT_ROI_mad                    0
                                   ...
LMSPRODUCT_STLAP_mad                  0
LMSPRODUCT_STLAP_std               1086
LMSPRODUCT_LAP_mean                   0
LMSPRODUCT_LAP_sum                    0
LMSPRODUCT_LAP_min                    0
LMSPRODUCT_LAP_max                    0
LMSPRODUCT_LAP_median                 0
LMSPRODUCT_LAP_quantile               0
LMSPRODUCT_LAP_mad                    0
LMSPRODUCT_LAP_std                 1086
LMSlast_auth_d_mean                   0
LMSlast_auth_d_sum                    0
LMSlast_auth_d_min                    0
LMSlast_auth_d_max                    0
LMSlast_auth_d_median                 0
LMSlast_auth_d_quantile               0
LMSlast_auth_d_mad                    0
LMSlast_auth_d_std                 1086
LMSlast_auth_m_mean                   0
LMSlast_auth_m_sum                    0
LMSlast_auth_m_min                    0
LMSlast_auth_m_max                    0
LMSlast_auth_m_median                 0
LMSlast_auth_m_quantile               0
LMSlast_auth_m_mad                    0
LMSlast_auth_m_std                 1086
LMSNPA_IN_LAST_MONTH_count            0
LMSNPA_IN_LAST_MONTH_nunique          0
LMSNPA_IN_CURRENT_MONTH_count         0
LMSNPA_IN_CURRENT_MONTH_nunique       0
Length: 371, dtype: int64

In [20]:
# print(len(np.intersect1d(cust1['CUSTOMERID'].values,df_train.CUSTOMERID)))

In [21]:
# # cust1['BRANCH_PINCODE'].value_counts()
# # cust1
# cust1['AGE'].fillna(cust1['AGE'].mean(),inplace=True)
# cust1['SEX'].fillna('O',inplace=True)
# cust1['MARITAL_STATUS'].fillna('O',inplace=True)
# cust1['NO_OF_DEPENDENT'].fillna(0,inplace=True)
# cust1['QUALIFICATION'].fillna('OTHER',inplace=True)
# cust1['BRANCH_PINCODE']=cust1['BRANCH_PINCODE'].astype(np.object)
# cust1['CUST_CONSTTYPE_ID']=cust1['CUST_CONSTTYPE_ID'].astype(np.object)
# cust1['CUST_CATEGORYID']=cust1['CUST_CATEGORYID'].astype(np.object)
# cust1['BRANCH_PINCODE'].fillna('0',inplace=True)
# cust1.info()

In [22]:
df_train=df.merge(train,on=['AGREEMENTID'])
df_test=df.merge(test,on=['AGREEMENTID']).drop('FORECLOSURE',axis=1)
# del df_test

In [23]:
df_train.head()

   AGREEMENTID     ...       FORECLOSURE
0     11220001     ...                 1
1     11220002     ...                 1
2     11220006     ...                 1
3     11220008     ...                 1
4     11220010     ...                 1

[5 rows x 372 columns]

In [24]:
df_train.isnull().sum()

AGREEMENTID                          0
LMSCUSTOMERID_sum                    0
LMSCUSTOMERID_mean                   0
LMSCUSTOMERID_count                  0
LMSCUSTOMERID_nunique                0
LMSCUSTOMERID_min                    0
LMSCUSTOMERID_max                    0
LMSLOAN_AMT_mean                     0
LMSLOAN_AMT_sum                      0
LMSLOAN_AMT_min                      0
LMSLOAN_AMT_max                      0
LMSLOAN_AMT_median                   0
LMSLOAN_AMT_quantile                 0
LMSLOAN_AMT_mad                      0
LMSLOAN_AMT_std                    665
LMSNET_DISBURSED_AMT_mean            0
LMSNET_DISBURSED_AMT_sum             0
LMSNET_DISBURSED_AMT_min             0
LMSNET_DISBURSED_AMT_max             0
LMSNET_DISBURSED_AMT_median          0
LMSNET_DISBURSED_AMT_quantile        0
LMSNET_DISBURSED_AMT_mad             0
LMSNET_DISBURSED_AMT_std           665
LMSCURRENT_ROI_mean                  0
LMSCURRENT_ROI_sum                   0
LMSCURRENT_ROI_min                   0
LMSCURRENT_ROI_max                   0
LMSCURRENT_ROI_median                0
LMSCURRENT_ROI_quantile              0
LMSCURRENT_ROI_mad                   0
                                  ...
LMSPRODUCT_STLAP_std               665
LMSPRODUCT_LAP_mean                  0
LMSPRODUCT_LAP_sum                   0
LMSPRODUCT_LAP_min                   0
LMSPRODUCT_LAP_max                   0
LMSPRODUCT_LAP_median                0
LMSPRODUCT_LAP_quantile              0
LMSPRODUCT_LAP_mad                   0
LMSPRODUCT_LAP_std                 665
LMSlast_auth_d_mean                  0
LMSlast_auth_d_sum                   0
LMSlast_auth_d_min                   0
LMSlast_auth_d_max                   0
LMSlast_auth_d_median                0
LMSlast_auth_d_quantile              0
LMSlast_auth_d_mad                   0
LMSlast_auth_d_std                 665
LMSlast_auth_m_mean                  0
LMSlast_auth_m_sum                   0
LMSlast_auth_m_min                   0
LMSlast_auth_m_max                   0
LMSlast_auth_m_median                0
LMSlast_auth_m_quantile              0
LMSlast_auth_m_mad                   0
LMSlast_auth_m_std                 665
LMSNPA_IN_LAST_MONTH_count           0
LMSNPA_IN_LAST_MONTH_nunique         0
LMSNPA_IN_CURRENT_MONTH_count        0
LMSNPA_IN_CURRENT_MONTH_nunique      0
FORECLOSURE                          0
Length: 372, dtype: int64

In [25]:
# tran['PRODUCT'].value_counts()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13342 entries, 0 to 13341
Columns: 371 entries, AGREEMENTID to LMSNPA_IN_CURRENT_MONTH_nunique
dtypes: float64(320), int64(37), uint8(14)
memory usage: 36.6 MB

In [26]:
# df_train['LOAN_AMT']-df_train['NET_DISBURSED_AMT']
# df_train.isnull().sum()

In [27]:
# df_train['CUSTOMERID']=df_train['CUSTOMERID'].astype(np.object)
# df_train['CUSTOMERID'].fillna('1200XXXX',inplace=True)
# df_train['SCHEMEID']=df_train['SCHEMEID'].astype(np.object)
# df_train['SCHEMEID'].fillna('1090XXXX',inplace=True)
# df_train['LAST_RECEIPT_AMOUNT'].fillna(df_train['LAST_RECEIPT_AMOUNT'].mean(),inplace=True)

# df_train['ROI_DIFF']=df_train['CURRENT_ROI']-df_train['ORIGNAL_ROI']
# df_train['TENOR_DIFF']=df_train['CURRENT_TENOR']-df_train['ORIGNAL_TENOR']
# df_train['AMT_DIFF']=df_train['LOAN_AMT']-df_train['NET_DISBURSED_AMT']

# df_test['CUSTOMERID']=df_test['CUSTOMERID'].astype(np.object)
# df_test['CUSTOMERID'].fillna('1200XXXX',inplace=True)
# df_test['SCHEMEID']=df_test['SCHEMEID'].astype(np.object)
# df_test['SCHEMEID'].fillna('1090XXXX',inplace=True)
# df_test['LAST_RECEIPT_AMOUNT'].fillna(df_test['LAST_RECEIPT_AMOUNT'].mean(),inplace=True)
# df_test['DPD'].fillna(df_test['DPD'].mean(),inplace=True)
# df_test['ROI_DIFF']=df_test['CURRENT_ROI']-df_test['ORIGNAL_ROI']
# df_test['TENOR_DIFF']=df_test['CURRENT_TENOR']-df_test['ORIGNAL_TENOR']
# df_test['AMT_DIFF']=df_test['LOAN_AMT']-df_test['NET_DISBURSED_AMT']

### Evaluating and Predicting

In [28]:
from catboost import CatBoostClassifier,Pool, cv
from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold,train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score

In [29]:
X_train,X_val,y_train,y_val = train_test_split(df_train.drop(['AGREEMENTID','FORECLOSURE'],axis=1),df_train['FORECLOSURE'],
                                                 test_size=0.25,random_state = 1994)

In [30]:
# y.value_counts()

In [31]:
categorical_features_indices = np.where(X_train.dtypes =='object')[0]
categorical_features_indices

array([], dtype=int64)

In [32]:
# cat_model = CatBoostClassifier(n_estimators=1000, # use large n_estimators deliberately to make use of the early stopping
# #                          reg_lambda=0.25,
# #                          l2_leaf_reg=10.0,
# #                         custom_metric= ['AUC','Logloss'],
#                          eval_metric='AUC',
#                          random_seed=1994,
# #                          learning_rate = 0.12,
#                          depth = 6,
# #                                class_weights=[1,20],
# #                                boosting_type = 'Ordered',
# #                          subsample = 0.8
#                          #rsm = 0.7,
#                          #silent=True,
#                          #max_ctr_complexity = 5,  # no of categorical cols combined
# #                          boosting_type = 'Ordered',
# #                          od_type = 'IncToDec',  #overfitting params
# #                          od_wait = 20,
#                          bagging_temperature = 1.0
#                               )
# # lr=0.05, no od type of vars -- highest
    
# cat_model.fit(X_train.values,y_train.values,cat_features=categorical_features_indices,eval_set=(X_val, y_val),
#         plot=False,early_stopping_rounds=100,use_best_model=True,verbose=50) # early stopping set to 100 to prevent overfitting

In [33]:
# m=LGBMClassifier(n_estimators=1500,random_state=1994,learning_rate=0.03,max_depth=7,num_leaves=100,reg_alpha=2)
m=LGBMClassifier(n_estimators=1500,random_state=1994)
# m=RidgeCV(cv=4)
m.fit(X_train,y_train,eval_set=[(X_val, y_val.values)],eval_metric='auc', early_stopping_rounds=100,verbose=100)
p=m.predict_proba(X_val)[:,-1]
# m=Rid
# print(np.sqrt(mean_squared_log_error(np.expm1(y_val.values),np.expm1(p))))
# print(np.sqrt(mean_squared_log_error(y_val.values,p)))
print(roc_auc_score(y_val,p))

Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.995478	valid_0's binary_logloss: 0.0280304
Early stopping, best iteration is:
[77]	valid_0's auc: 0.995347	valid_0's binary_logloss: 0.0277418
0.9953467724328652

In [34]:
sorted(zip(m.feature_importances_,X_train),reverse=True)

[(371, 'LMSCUSTOMERID_mean'),
 (191, 'LMSSCHEMEID_mean'),
 (159, 'LMSCUSTOMERID_sum'),
 (85, 'LMSPRODUCT_LAP_mean'),
 (58, 'LMSPRODUCT_STLAP_mean'),
 (48, 'LMSPRODUCT_STHL_sum'),
 (34, 'LMSNET_LTV_mean'),
 (32, 'LMSROI_DIFF_std'),
 (32, 'LMSNET_LTV_sum'),
 (30, 'LMSROI_DIFF_sum'),
 (30, 'LMSFOIR_mean'),
 (28, 'LMSPAID_INTEREST_sum'),
 (24, 'LMSPRODUCT_LAP_sum'),
 (23, 'LMSlast_int_d_min'),
 (23, 'LMSlast_auth_y_sum'),
 (23, 'LMSOUTSTANDING_PRINCIPAL_mad'),
 (22, 'LMSlast_auth_y_median'),
 (21, 'LMSCUSTOMERID_count'),
 (21, 'LMSCURRENT_ROI_mean'),
 (20, 'LMSlast_int_d_sum'),
 (20, 'LMSlast_auth_y_mean'),
 (20, 'LMSauth_int_d_mean'),
 (20, 'LMSBALANCE_TENURE_min'),
 (19, 'LMSauth_int_d_mad'),
 (19, 'LMSLAST_RECEIPT_AMOUNT_std'),
 (19, 'LMSCURRENT_ROI_mad'),
 (18, 'LMSlast_auth_y_min'),
 (18, 'LMSLAST_RECEIPT_AMOUNT_mean'),
 (18, 'LMSBALANCE_TENURE_mean'),
 (17, 'LMSSCHEMEID_sum'),
 (17, 'LMSCITY_sum'),
 (16, 'LMSPRODUCT_STLAP_sum'),
 (15, 'LMSlast_auth_y_std'),
 (15, 'LMSLAST_RECEIPT_AMOUNT_mad'),
 (15, 'LMSBALANCE_EXCESS_mean'),
 (14, 'LMSTENOR_DIFF_mean'),
 (14, 'LMSMOB_sum'),
 (14, 'LMSLAST_RECEIPT_AMOUNT_median'),
 (13, 'LMSlast_int_d_mean'),
 (13, 'LMSORIGNAL_ROI_max'),
 (13, 'LMSNET_RECEIVABLE_mean'),
 (13, 'LMSFOIR_sum'),
 (13, 'LMSCURRENT_ROI_sum'),
 (13, 'LMSCURRENT_ROI_std'),
 (12, 'LMSLAST_RECEIPT_AMOUNT_max'),
 (12, 'LMSBALANCE_EXCESS_sum'),
 (11, 'LMSPAID_INTEREST_min'),
 (11, 'LMSNET_RECEIVABLE_sum'),
 (11, 'LMSMOB_mean'),
 (11, 'LMSDUEDAY_sum'),
 (11, 'LMSCURRENT_ROI_min'),
 (11, 'LMSCURRENT_ROI_max'),
 (10, 'LMSlast_auth_y_max'),
 (10, 'LMSNPA_IN_LAST_MONTH_count'),
 (10, 'LMSCOMPLETED_TENURE_mean'),
 (10, 'LMSBALANCE_EXCESS_max'),
 (9, 'LMSlast_int_d_std'),
 (9, 'LMSPRE_EMI_DUEAMT_sum'),
 (9, 'LMSPRE_EMI_DUEAMT_median'),
 (9, 'LMSPAID_PRINCIPAL_sum'),
 (9, 'LMSPAID_INTEREST_max'),
 (9, 'LMSOUTSTANDING_PRINCIPAL_std'),
 (9, 'LMSORIGNAL_ROI_sum'),
 (9, 'LMSNET_RECEIVABLE_min'),
 (9, 'LMSMONTHOPENING_std'),
 (9, 'LMSBALANCE_TENURE_mad'),
 (8, 'LMSPAID_INTEREST_mean'),
 (8, 'LMSLAST_RECEIPT_AMOUNT_sum'),
 (8, 'LMSCOMPLETED_TENURE_std'),
 (8, 'LMSBALANCE_TENURE_sum'),
 (8, 'LMSAMT_DIFF_sum'),
 (7, 'LMSROI_DIFF_min'),
 (7, 'LMSROI_DIFF_mean'),
 (7, 'LMSROI_DIFF_max'),
 (7, 'LMSPRE_EMI_RECEIVED_AMT_std'),
 (7, 'LMSPRE_EMI_DUEAMT_std'),
 (7, 'LMSOUTSTANDING_PRINCIPAL_min'),
 (7, 'LMSOUTSTANDING_PRINCIPAL_median'),
 (7, 'LMSNET_RECEIVABLE_mad'),
 (7, 'LMSNET_LTV_median'),
 (7, 'LMSNET_DISBURSED_AMT_min'),
 (7, 'LMSLAST_RECEIPT_AMOUNT_min'),
 (7, 'LMSBALANCE_EXCESS_mad'),
 (6, 'LMSlast_int_m_mean'),
 (6, 'LMSPRE_EMI_RECEIVED_AMT_median'),
 (6, 'LMSPRE_EMI_DUEAMT_min'),
 (6, 'LMSPRE_EMI_DUEAMT_max'),
 (6, 'LMSORIGNAL_ROI_mean'),
 (6, 'LMSNET_RECEIVABLE_median'),
 (6, 'LMSNET_DISBURSED_AMT_mad'),
 (6, 'LMSMONTHOPENING_mad'),
 (6, 'LMSLOAN_AMT_sum'),
 (6, 'LMSEXCESS_AVAILABLE_mad'),
 (6, 'LMSCURRENT_ROI_median'),
 (6, 'LMSCITY_mean'),
 (6, 'LMSBALANCE_EXCESS_median'),
 (5, 'LMSlast_int_m_std'),
 (5, 'LMSlast_auth_y_mad'),
 (5, 'LMSauth_int_d_std'),
 (5, 'LMSPRE_EMI_DUEAMT_mad'),
 (5, 'LMSPAID_PRINCIPAL_median'),
 (5, 'LMSORIGNAL_TENOR_sum'),
 (5, 'LMSNET_RECEIVABLE_std'),
 (5, 'LMSLOAN_AMT_mad'),
 (5, 'LMSEXCESS_AVAILABLE_std'),
 (5, 'LMSEXCESS_ADJUSTED_AMT_sum'),
 (5, 'LMSAMT_DIFF_mean'),
 (4, 'LMSlast_int_y_mean'),
 (4, 'LMSlast_int_y_mad'),
 (4, 'LMSlast_int_d_mad'),
 (4, 'LMSPAID_PRINCIPAL_mean'),
 (4, 'LMSPAID_INTEREST_mad'),
 (4, 'LMSNET_LTV_mad'),
 (4, 'LMSMONTHOPENING_min'),
 (4, 'LMSLOAN_AMT_mean'),
 (4, 'LMSEMI_RECEIVED_AMT_sum'),
 (4, 'LMSEMI_DUEAMT_median'),
 (4, 'LMSDPD_median'),
 (4, 'LMSCOMPLETED_TENURE_sum'),
 (4, 'LMSCOMPLETED_TENURE_mad'),
 (4, 'LMSBALANCE_TENURE_std'),
 (4, 'LMSBALANCE_TENURE_median'),
 (3, 'LMSlast_int_m_sum'),
 (3, 'LMSROI_DIFF_mad'),
 (3, 'LMSPRODUCT_STHL_mean'),
 (3, 'LMSPAID_PRINCIPAL_max'),
 (3, 'LMSPAID_INTEREST_median'),
 (3, 'LMSORIGNAL_ROI_mad'),
 (3, 'LMSLOAN_AMT_max'),
 (3, 'LMSFOIR_mad'),
 (3, 'LMSEXCESS_AVAILABLE_sum'),
 (3, 'LMSEMI_RECEIVED_AMT_mean'),
 (3, 'LMSDPD_mean'),
 (3, 'LMSCURRENT_TENOR_sum'),
 (3, 'LMSCOMPLETED_TENURE_min'),
 (3, 'LMSCOMPLETED_TENURE_median'),
 (3, 'LMSBALANCE_TENURE_max'),
 (2, 'LMSlast_int_y_sum'),
 (2, 'LMSlast_int_d_median'),
 (2, 'LMSTENOR_DIFF_sum'),
 (2, 'LMSTENOR_DIFF_min'),
 (2, 'LMSTENOR_DIFF_max'),
 (2, 'LMSPRE_EMI_RECEIVED_AMT_sum'),
 (2, 'LMSPRE_EMI_RECEIVED_AMT_mean'),
 (2, 'LMSPRE_EMI_RECEIVED_AMT_mad'),
 (2, 'LMSPRE_EMI_OS_AMOUNT_std'),
 (2, 'LMSPAID_PRINCIPAL_std'),
 (2, 'LMSPAID_INTEREST_std'),
 (2, 'LMSEXCESS_AVAILABLE_median'),
 (2, 'LMSEMI_RECEIVED_AMT_mad'),
 (2, 'LMSCURRENT_TENOR_std'),
 (2, 'LMSCURRENT_TENOR_mean'),
 (2, 'LMSCURRENT_TENOR_max'),
 (2, 'LMSCURRENT_TENOR_mad'),
 (2, 'LMSBALANCE_EXCESS_std'),
 (1, 'LMSlast_auth_m_mad'),
 (1, 'LMSTENOR_DIFF_median'),
 (1, 'LMSPRE_EMI_RECEIVED_AMT_max'),
 (1, 'LMSPAID_PRINCIPAL_min'),
 (1, 'LMSPAID_PRINCIPAL_mad'),
 (1, 'LMSOUTSTANDING_PRINCIPAL_mean'),
 (1, 'LMSORIGNAL_ROI_min'),
 (1, 'LMSNET_LTV_min'),
 (1, 'LMSNET_LTV_max'),
 (1, 'LMSNET_DISBURSED_AMT_mean'),
 (1, 'LMSMONTHOPENING_sum'),
 (1, 'LMSEXCESS_AVAILABLE_mean'),
 (1, 'LMSEXCESS_AVAILABLE_max'),
 (1, 'LMSEXCESS_ADJUSTED_AMT_std'),
 (1, 'LMSEXCESS_ADJUSTED_AMT_median'),
 (1, 'LMSEXCESS_ADJUSTED_AMT_max'),
 (1, 'LMSEXCESS_ADJUSTED_AMT_mad'),
 (1, 'LMSEMI_RECEIVED_AMT_std'),
 (1, 'LMSEMI_RECEIVED_AMT_median'),
 (1, 'LMSEMI_RECEIVED_AMT_max'),
 (1, 'LMSEMI_OS_AMOUNT_sum'),
 (1, 'LMSEMI_OS_AMOUNT_mean'),
 (1, 'LMSEMI_DUEAMT_sum'),
 (1, 'LMSEMI_DUEAMT_std'),
 (1, 'LMSEMI_DUEAMT_max'),
 (1, 'LMSEMI_DUEAMT_mad'),
 (1, 'LMSDPD_std'),
 (1, 'LMSDPD_mad'),
 (1, 'LMSCITY_min'),
 (1, 'LMSCITY_max'),
 (1, 'LMSAMT_DIFF_max'),
 (0, 'LMSlast_int_y_std'),
 (0, 'LMSlast_int_y_quantile'),
 (0, 'LMSlast_int_y_min'),
 (0, 'LMSlast_int_y_median'),
 (0, 'LMSlast_int_y_max'),
 (0, 'LMSlast_int_m_quantile'),
 (0, 'LMSlast_int_m_min'),
 (0, 'LMSlast_int_m_median'),
 (0, 'LMSlast_int_m_max'),
 (0, 'LMSlast_int_m_mad'),
 (0, 'LMSlast_int_d_quantile'),
 (0, 'LMSlast_int_d_max'),
 (0, 'LMSlast_auth_y_quantile'),
 (0, 'LMSlast_auth_m_sum'),
 (0, 'LMSlast_auth_m_std'),
 (0, 'LMSlast_auth_m_quantile'),
 (0, 'LMSlast_auth_m_min'),
 (0, 'LMSlast_auth_m_median'),
 (0, 'LMSlast_auth_m_mean'),
 (0, 'LMSlast_auth_m_max'),
 (0, 'LMSlast_auth_d_sum'),
 (0, 'LMSlast_auth_d_std'),
 (0, 'LMSlast_auth_d_quantile'),
 (0, 'LMSlast_auth_d_min'),
 (0, 'LMSlast_auth_d_median'),
 (0, 'LMSlast_auth_d_mean'),
 (0, 'LMSlast_auth_d_max'),
 (0, 'LMSlast_auth_d_mad'),
 (0, 'LMSauth_int_y_sum'),
 (0, 'LMSauth_int_y_std'),
 (0, 'LMSauth_int_y_quantile'),
 (0, 'LMSauth_int_y_min'),
 (0, 'LMSauth_int_y_median'),
 (0, 'LMSauth_int_y_mean'),
 (0, 'LMSauth_int_y_max'),
 (0, 'LMSauth_int_y_mad'),
 (0, 'LMSauth_int_m_sum'),
 (0, 'LMSauth_int_m_std'),
 (0, 'LMSauth_int_m_quantile'),
 (0, 'LMSauth_int_m_min'),
 (0, 'LMSauth_int_m_median'),
 (0, 'LMSauth_int_m_mean'),
 (0, 'LMSauth_int_m_max'),
 (0, 'LMSauth_int_m_mad'),
 (0, 'LMSauth_int_d_sum'),
 (0, 'LMSauth_int_d_quantile'),
 (0, 'LMSauth_int_d_min'),
 (0, 'LMSauth_int_d_median'),
 (0, 'LMSauth_int_d_max'),
 (0, 'LMSTENOR_DIFF_std'),
 (0, 'LMSTENOR_DIFF_quantile'),
 (0, 'LMSTENOR_DIFF_mad'),
 (0, 'LMSSCHEMEID_nunique'),
 (0, 'LMSSCHEMEID_min'),
 (0, 'LMSSCHEMEID_max'),
 (0, 'LMSSCHEMEID_count'),
 (0, 'LMSROI_DIFF_quantile'),
 (0, 'LMSROI_DIFF_median'),
 (0, 'LMSPRODUCT_STLAP_std'),
 (0, 'LMSPRODUCT_STLAP_quantile'),
 (0, 'LMSPRODUCT_STLAP_min'),
 (0, 'LMSPRODUCT_STLAP_median'),
 (0, 'LMSPRODUCT_STLAP_max'),
 (0, 'LMSPRODUCT_STLAP_mad'),
 (0, 'LMSPRODUCT_STHL_std'),
 (0, 'LMSPRODUCT_STHL_quantile'),
 (0, 'LMSPRODUCT_STHL_min'),
 (0, 'LMSPRODUCT_STHL_median'),
 (0, 'LMSPRODUCT_STHL_max'),
 (0, 'LMSPRODUCT_STHL_mad'),
 (0, 'LMSPRODUCT_LAP_std'),
 (0, 'LMSPRODUCT_LAP_quantile'),
 (0, 'LMSPRODUCT_LAP_min'),
 (0, 'LMSPRODUCT_LAP_median'),
 (0, 'LMSPRODUCT_LAP_max'),
 (0, 'LMSPRODUCT_LAP_mad'),
 (0, 'LMSPRE_EMI_RECEIVED_AMT_quantile'),
 (0, 'LMSPRE_EMI_RECEIVED_AMT_min'),
 (0, 'LMSPRE_EMI_OS_AMOUNT_sum'),
 (0, 'LMSPRE_EMI_OS_AMOUNT_quantile'),
 (0, 'LMSPRE_EMI_OS_AMOUNT_min'),
 (0, 'LMSPRE_EMI_OS_AMOUNT_median'),
 (0, 'LMSPRE_EMI_OS_AMOUNT_mean'),
 (0, 'LMSPRE_EMI_OS_AMOUNT_max'),
 (0, 'LMSPRE_EMI_OS_AMOUNT_mad'),
 (0, 'LMSPRE_EMI_DUEAMT_quantile'),
 (0, 'LMSPRE_EMI_DUEAMT_mean'),
 (0, 'LMSPAID_PRINCIPAL_quantile'),
 (0, 'LMSPAID_INTEREST_quantile'),
 (0, 'LMSOUTSTANDING_PRINCIPAL_sum'),
 (0, 'LMSOUTSTANDING_PRINCIPAL_quantile'),
 (0, 'LMSOUTSTANDING_PRINCIPAL_max'),
 (0, 'LMSORIGNAL_TENOR_std'),
 (0, 'LMSORIGNAL_TENOR_quantile'),
 (0, 'LMSORIGNAL_TENOR_min'),
 (0, 'LMSORIGNAL_TENOR_median'),
 (0, 'LMSORIGNAL_TENOR_mean'),
 (0, 'LMSORIGNAL_TENOR_max'),
 (0, 'LMSORIGNAL_TENOR_mad'),
 (0, 'LMSORIGNAL_ROI_std'),
 (0, 'LMSORIGNAL_ROI_quantile'),
 (0, 'LMSORIGNAL_ROI_median'),
 (0, 'LMSNPA_IN_LAST_MONTH_nunique'),
 (0, 'LMSNPA_IN_CURRENT_MONTH_nunique'),
 (0, 'LMSNPA_IN_CURRENT_MONTH_count'),
 (0, 'LMSNET_RECEIVABLE_quantile'),
 (0, 'LMSNET_RECEIVABLE_max'),
 (0, 'LMSNET_LTV_std'),
 (0, 'LMSNET_LTV_quantile'),
 (0, 'LMSNET_DISBURSED_AMT_sum'),
 (0, 'LMSNET_DISBURSED_AMT_std'),
 (0, 'LMSNET_DISBURSED_AMT_quantile'),
 (0, 'LMSNET_DISBURSED_AMT_median'),
 (0, 'LMSNET_DISBURSED_AMT_max'),
 (0, 'LMSMONTHOPENING_quantile'),
 (0, 'LMSMONTHOPENING_median'),
 (0, 'LMSMONTHOPENING_mean'),
 (0, 'LMSMONTHOPENING_max'),
 (0, 'LMSMOB_nunique'),
 (0, 'LMSMOB_min'),
 (0, 'LMSMOB_max'),
 (0, 'LMSMOB_count'),
 (0, 'LMSLOAN_AMT_std'),
 (0, 'LMSLOAN_AMT_quantile'),
 (0, 'LMSLOAN_AMT_min'),
 (0, 'LMSLOAN_AMT_median'),
 (0, 'LMSLAST_RECEIPT_AMOUNT_quantile'),
 (0, 'LMSIS_TRAN_FINAL_AGG_sum'),
 (0, 'LMSIS_TRAN_FINAL_AGG_std'),
 (0, 'LMSIS_TRAN_FINAL_AGG_quantile'),
 (0, 'LMSIS_TRAN_FINAL_AGG_min'),
 (0, 'LMSIS_TRAN_FINAL_AGG_median'),
 (0, 'LMSIS_TRAN_FINAL_AGG_mean'),
 (0, 'LMSIS_TRAN_FINAL_AGG_max'),
 (0, 'LMSIS_TRAN_FINAL_AGG_mad'),
 (0, 'LMSFOIR_std'),
 (0, 'LMSFOIR_quantile'),
 (0, 'LMSFOIR_min'),
 (0, 'LMSFOIR_median'),
 (0, 'LMSFOIR_max'),
 (0, 'LMSEXCESS_AVAILABLE_quantile'),
 (0, 'LMSEXCESS_AVAILABLE_min'),
 (0, 'LMSEXCESS_ADJUSTED_AMT_quantile'),
 (0, 'LMSEXCESS_ADJUSTED_AMT_min'),
 (0, 'LMSEXCESS_ADJUSTED_AMT_mean'),
 (0, 'LMSEMI_RECEIVED_AMT_quantile'),
 (0, 'LMSEMI_RECEIVED_AMT_min'),
 (0, 'LMSEMI_OS_AMOUNT_std'),
 (0, 'LMSEMI_OS_AMOUNT_quantile'),
 (0, 'LMSEMI_OS_AMOUNT_min'),
 (0, 'LMSEMI_OS_AMOUNT_median'),
 (0, 'LMSEMI_OS_AMOUNT_max'),
 (0, 'LMSEMI_OS_AMOUNT_mad'),
 (0, 'LMSEMI_DUEAMT_quantile'),
 (0, 'LMSEMI_DUEAMT_min'),
 (0, 'LMSEMI_DUEAMT_mean'),
 (0, 'LMSDUEDAY_nunique'),
 (0, 'LMSDUEDAY_min'),
 (0, 'LMSDUEDAY_mean'),
 (0, 'LMSDUEDAY_max'),
 (0, 'LMSDUEDAY_count'),
 (0, 'LMSDPD_sum'),
 (0, 'LMSDPD_quantile'),
 (0, 'LMSDPD_min'),
 (0, 'LMSDPD_max'),
 (0, 'LMSCUSTOMERID_nunique'),
 (0, 'LMSCUSTOMERID_min'),
 (0, 'LMSCUSTOMERID_max'),
 (0, 'LMSCURRENT_TENOR_quantile'),
 (0, 'LMSCURRENT_TENOR_min'),
 (0, 'LMSCURRENT_TENOR_median'),
 (0, 'LMSCURRENT_ROI_quantile'),
 (0, 'LMSCOMPLETED_TENURE_quantile'),
 (0, 'LMSCOMPLETED_TENURE_max'),
 (0, 'LMSCITY_nunique'),
 (0, 'LMSCITY_count'),
 (0, 'LMSBALANCE_TENURE_quantile'),
 (0, 'LMSBALANCE_EXCESS_quantile'),
 (0, 'LMSBALANCE_EXCESS_min'),
 (0, 'LMSAMT_DIFF_std'),
 (0, 'LMSAMT_DIFF_quantile'),
 (0, 'LMSAMT_DIFF_min'),
 (0, 'LMSAMT_DIFF_median'),
 (0, 'LMSAMT_DIFF_mad')]

In [35]:
# preds = cat_model.predict_proba(X_val)[:,1]
# print(roc_auc_score(y_val,preds))

In [36]:
#LGB
# X_train,X_val,y_train,y_val = train_test_split(df_train.drop(['AGREEMENTID','FORECLOSURE','CUSTOMERID','SCHEMEID'],axis=1),df_train['FORECLOSURE'],
#                                                  test_size=0.25,random_state = 1994)
# import lightgbm as lgb
# from lightgbm import LGBMModel,LGBMClassifier

# X,y=df_train.drop(['AGREEMENTID','FORECLOSURE','CUSTOMERID','SCHEMEID'],axis=1),df_train['FORECLOSURE']
# Xtest=df_test.drop(['AGREEMENTID','CUSTOMERID','SCHEMEID'],axis=1)

# lgbc = LGBMClassifier(n_estimators=300, random_state =1994,metrics ='auc')
# fit_model = lgbc.fit(X, y)
# y_test_pred = fit_model.predict_proba(Xtest)[:,1]
# print(roc_auc_score(y_val,y_test_pred))

In [37]:
X,y=df_train.drop(['AGREEMENTID','FORECLOSURE'],axis=1),df_train['FORECLOSURE']
Xtest=df_test.drop(['AGREEMENTID'],axis=1)

print(X.shape,Xtest.shape)

(20012, 370) (13342, 370)

In [38]:
# m.fit(X,y,eval_set=(X, y),early_stopping_rounds=100,verbose=100,eval_metric='auc')
# y_pred=cat_model.predict_proba(Xtest)[:,1]

In [39]:
# s=pd.DataFrame({'AGREEMENTID':test['AGREEMENTID'],'FORECLOSURE':y_pred})

# # s.to_csv('catboost1.csv',index=False) --main 62 max depth-8 lr-0.1
# # s.to_csv('catboostBasicnewbest.csv',index=False)
# s.to_csv('lgbmbasic.csv',index=False)
# s.head()

In [40]:

err=[]
y_pred_tot=[]
from sklearn.model_selection import KFold,StratifiedKFold
fold=StratifiedKFold(n_splits=30,shuffle=True,random_state=1994)
i=1
for train_index, test_index in fold.split(X,y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
#     cat_model5 = CatBoostClassifier(n_estimators=1000,eval_metric='AUC',random_seed=1994,depth=6,bagging_temperature = 1.0)
#     cat_model5.fit(X_train.values,y_train.values,cat_features=categorical_features_indices,eval_set=(X_test, y_test),
#         plot=False,early_stopping_rounds=100,use_best_model=True,verbose=100) # early stopping set to 100 to prevent overfitting
#     preds = cat_model5.predict_proba(X_test)[:,1]
    
#     m=LGBMClassifier(n_estimators=1500,random_state=1994,learning_rate=0.03,max_depth=7,num_leaves=100,class_weight='balanced',reg_alpha=2)
    m=LGBMClassifier(n_estimators=1500,random_state=1994)
    # m=RidgeCV(cv=4)
    m.fit(X_train.values,y_train.values,eval_set=[(X_val, y_val.values)],eval_metric='auc', early_stopping_rounds=100,verbose=100)
    preds=m.predict_proba(X_test)[:,-1]
    
    print("err: ",roc_auc_score(y_test,preds))
    err.append(roc_auc_score(y_test,preds))
    p = m.predict_proba(Xtest)[:,-1]
#     s=pd.DataFrame({'AGREEMENTID':test['AGREEMENTID'],'FORECLOSURE':p})
#     s.to_csv('lgbmfoldsnew_xx'+str(i)+'.csv',index=False)
    i=i+1
    y_pred_tot.append(p)

Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00194227
Early stopping, best iteration is:
[52]	valid_0's auc: 1	valid_0's binary_logloss: 0.008957
err:  0.9972565157750344
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999796	valid_0's binary_logloss: 0.00323247
Early stopping, best iteration is:
[53]	valid_0's auc: 0.999877	valid_0's binary_logloss: 0.00971252
err:  0.9987997256515776
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999999	valid_0's binary_logloss: 0.00222937
[200]	valid_0's auc: 1	valid_0's binary_logloss: 0.000328897
Early stopping, best iteration is:
[107]	valid_0's auc: 1	valid_0's binary_logloss: 0.00189413
err:  0.9977709190672154
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00206919
Early stopping, best iteration is:
[77]	valid_0's auc: 1	valid_0's binary_logloss: 0.00395639
err:  0.9996951684194483
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999998	valid_0's binary_logloss: 0.00283218
[200]	valid_0's auc: 1	valid_0's binary_logloss: 0.000681212
Early stopping, best iteration is:
[139]	valid_0's auc: 1	valid_0's binary_logloss: 0.00135037
err:  0.9998094802621551
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00237285
Early stopping, best iteration is:
[82]	valid_0's auc: 1	valid_0's binary_logloss: 0.00366709
err:  0.9999237921048622
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00208846
Early stopping, best iteration is:
[57]	valid_0's auc: 1	valid_0's binary_logloss: 0.00800374
err:  0.9995046486816034
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999691	valid_0's binary_logloss: 0.00311421
[200]	valid_0's auc: 0.999783	valid_0's binary_logloss: 0.00193567
Early stopping, best iteration is:
[190]	valid_0's auc: 0.999796	valid_0's binary_logloss: 0.00188686
err:  0.9980376467001981
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00204449
Early stopping, best iteration is:
[55]	valid_0's auc: 1	valid_0's binary_logloss: 0.00831642
err:  0.9985711019661636
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999951	valid_0's binary_logloss: 0.00298168
[200]	valid_0's auc: 0.999999	valid_0's binary_logloss: 0.00128132
[300]	valid_0's auc: 0.999999	valid_0's binary_logloss: 0.00149668
Early stopping, best iteration is:
[231]	valid_0's auc: 0.999999	valid_0's binary_logloss: 0.00123722
err:  0.9977899710409999
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999542	valid_0's binary_logloss: 0.00405768
[200]	valid_0's auc: 0.999538	valid_0's binary_logloss: 0.00310695
Early stopping, best iteration is:
[173]	valid_0's auc: 0.999587	valid_0's binary_logloss: 0.00298103
err:  0.9966849565614999
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00200931
Early stopping, best iteration is:
[50]	valid_0's auc: 1	valid_0's binary_logloss: 0.00963758
err:  0.9984377381496722
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00207183
Early stopping, best iteration is:
[52]	valid_0's auc: 1	valid_0's binary_logloss: 0.00955062
err:  0.9998475842097241
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00231857
Early stopping, best iteration is:
[53]	valid_0's auc: 1	valid_0's binary_logloss: 0.00944506
err:  0.9948750190519738
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00233669
[200]	valid_0's auc: 1	valid_0's binary_logloss: 0.000466416
Early stopping, best iteration is:
[103]	valid_0's auc: 1	valid_0's binary_logloss: 0.00216737
err:  0.9998285322359397
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00224527
Early stopping, best iteration is:
[95]	valid_0's auc: 1	valid_0's binary_logloss: 0.00258371
err:  0.9985139460448104
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999219	valid_0's binary_logloss: 0.00370841
Early stopping, best iteration is:
[39]	valid_0's auc: 0.999461	valid_0's binary_logloss: 0.0166677
err:  0.9955418381344308
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.99953	valid_0's binary_logloss: 0.00419833
Early stopping, best iteration is:
[49]	valid_0's auc: 0.999556	valid_0's binary_logloss: 0.0117582
err:  0.9966613247863249
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00189412
Early stopping, best iteration is:
[52]	valid_0's auc: 1	valid_0's binary_logloss: 0.00895704
err:  0.9839075854700854
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00199139
Early stopping, best iteration is:
[48]	valid_0's auc: 1	valid_0's binary_logloss: 0.010478
err:  0.9990842490842491
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999737	valid_0's binary_logloss: 0.0042412
[200]	valid_0's auc: 0.999856	valid_0's binary_logloss: 0.00313307
Early stopping, best iteration is:
[188]	valid_0's auc: 0.999881	valid_0's binary_logloss: 0.00305571
err:  0.9988198421297013
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999984	valid_0's binary_logloss: 0.00325206
[200]	valid_0's auc: 0.999999	valid_0's binary_logloss: 0.00210905
[300]	valid_0's auc: 1	valid_0's binary_logloss: 0.00238262
Early stopping, best iteration is:
[213]	valid_0's auc: 1	valid_0's binary_logloss: 0.0021099
err:  0.9996130629933447
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00188206
Early stopping, best iteration is:
[51]	valid_0's auc: 1	valid_0's binary_logloss: 0.0093696
err:  0.9986650673270392
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 1	valid_0's binary_logloss: 0.00196295
Early stopping, best iteration is:
[52]	valid_0's auc: 1	valid_0's binary_logloss: 0.00888115
err:  0.9999613062993346
Training until validation scores don't improve for 100 rounds.
[100]	valid_0's auc: 0.999432	valid_0's binary_logloss: 0.00538022
[200]	valid_0's auc: 0.999489	valid_0's binary_logloss: 0.00536705
Early stopping, best iteration is:
[133]	valid_0's auc: 0.999471	valid_0's binary_logloss: 0.0047738
err:  0.9958984677294537

In [41]:
err_avg=np.mean(err,0)
err_avg

0.9977399795950737

In [42]:
y_pred=np.mean(y_pred_tot,0)
y_pred

array([9.94584885e-01, 9.88631636e-01, 9.96660139e-01, ...,
       3.89689534e-04, 6.32465975e-04, 4.97484427e-04])

In [43]:
# y_test_pred=(y_test_pred+y_pred)/2

In [44]:


s=pd.DataFrame({'AGREEMENTID':test['AGREEMENTID'],'FORECLOSURE':y_pred})

# s.to_csv('catboost1.csv',index=False) --main 62 max depth-8 lr-0.1
s.to_csv('lgbmbestfoldsxxXX.csv',index=False)
s.head()

   AGREEMENTID  FORECLOSURE
0     11220003     0.994585
1     11220004     0.988632
2     11220005     0.996660
3     11220007     0.993270
4     11220009     0.000784